# Utiliser une image de base avec Node.js
FROM node:16

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier package.json et package-lock.json (si présent)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code de l'application
COPY . .

# Exposer le port que l'application utilise
EXPOSE 3000

# Définir la commande de lancement de l'application
CMD ["npm", "start"]
